### ISSUE TITLE
complex and simplified conversions | 繁简转换

### ISSUE THREAD

**Issue by Zuoqiu-Yingyi** [siyuan-community/ideas#5]
使用 [GitHub - BYVoid/OpenCC: Conversion between Traditional and Simplified Chinese](https://github.com/BYVoid/OpenCC) 库进行繁简转换

- 设置
  - 繁体配置 (下拉框)
    - `繁体`
    - `香港繁體`
    - `臺灣正體`
  - 地域用词转换 (开关)
- 块菜单
  - 简体->繁体
  - 繁体->简体
  - 繁体->日文字体
  - 日文字体->繁体

REF: [開放中文轉換 Open Chinese Convert (OpenCC)](https://opencc.byvoid.com/)

**Comment by Zuoqiu-Yingyi** [comment]
~~由于 openCC 在开发环境中暂时无法正常安装, 该插件的开发活动暂时挂起~~

已找到解决方案: [opencc-js - npm](https://www.npmjs.com/package/opencc-js)

```log
../../node_modules/.pnpm/opencc@1.1.3/node_modules/opencc: Running install script, failed in 2.8s
.../opencc@1.1.3/node_modules/opencc install$ node-pre-gyp install --fallback-to-build || node-pre-gyp rebuild
│ node-pre-gyp info it worked if it ends with ok
│ node-pre-gyp info using node-pre-gyp@0.14.0
│ node-pre-gyp info using node@20.3.0 | win32 | x64
│ node-pre-gyp WARN Using needle for node-pre-gyp https download
│ node-pre-gyp info check checked for "D:\Sync\GitHub\siyuan-packages-monorepo\workspace\node_modules\.pnpm\opencc@1.1.3\node_modules\opencc\build\Release\opencc.node" (not found)
│ node-pre-gyp http GET https://github.com/BYVoid/OpenCC/releases/download/1.1.3/opencc-v1.1.3-node-v115-win32-x64.tar.gz
│ node-pre-gyp http 404 https://github.com/BYVoid/OpenCC/releases/download/1.1.3/opencc-v1.1.3-node-v115-win32-x64.tar.gz
│ node-pre-gyp WARN Tried to download(404): https://github.com/BYVoid/OpenCC/releases/download/1.1.3/opencc-v1.1.3-node-v115-win32-x64.tar.gz
│ node-pre-gyp WARN Pre-built binaries not found for opencc@1.1.3 and node@20.3.0 (node-v115 ABI, unknown) (falling back to source compile with node-gyp)
│ node-pre-gyp http 404 status code downloading tarball https://github.com/BYVoid/OpenCC/releases/download/1.1.3/opencc-v1.1.3-node-v115-win32-x64.tar.gz
│ node-pre-gyp ERR! build error
│ node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd clean' (Error: spawn node-gyp.cmd ENOENT)
│ node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (D:\Sync\GitHub\siyuan-packages-monorepo\workspace\node_modules\.pnpm\node-pre-gyp@0.14.0\node_modules\node-pre-gyp\lib\util\compile.js:77:29)
│ node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:511:28)
│ node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
│ node-pre-gyp ERR! stack     at onErrorNT (node:internal/child_process:483:16)
│ node-pre-gyp ERR! stack     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
│ node-pre-gyp ERR! System Windows_NT 10.0.22621
│ node-pre-gyp ERR! command "C:\\App\\scoop\\apps\\nodejs\\current\\node.exe" "D:\\Sync\\GitHub\\siyuan-packages-monorepo\\workspace\\node_modules\\.pnpm\\node-pre-gyp@0.14.0\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallbac…  
│ node-pre-gyp ERR! cwd D:\Sync\GitHub\siyuan-packages-monorepo\workspace\node_modules\.pnpm\opencc@1.1.3\node_modules\opencc
│ node-pre-gyp ERR! node -v v20.3.0
│ Failed to execute 'node-gyp.cmd clean' (Error: spawn node-gyp.cmd ENOENT)
│ node-pre-gyp ERR! node-pre-gyp -v v0.14.0
│ node-pre-gyp ERR! not ok
│ node-pre-gyp info it worked if it ends with ok
│ node-pre-gyp info using node-pre-gyp@0.14.0
│ node-pre-gyp info using node@20.3.0 | win32 | x64
│ [opencc] Removing "D:\Sync\GitHub\siyuan-packages-monorepo\workspace\node_modules\.pnpm\opencc@1.1.3\node_modules\opencc\build\Release"
│ node-pre-gyp ERR! build error
│ node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd clean' (Error: spawn node-gyp.cmd ENOENT)
│ node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (D:\Sync\GitHub\siyuan-packages-monorepo\workspace\node_modules\.pnpm\node-pre-gyp@0.14.0\node_modules\node-pre-gyp\lib\util\compile.js:77:29)
│ node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:511:28)
│ node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
│ node-pre-gyp ERR! stack     at onErrorNT (node:internal/child_process:483:16)
│ node-pre-gyp ERR! stack     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
│ node-pre-gyp ERR! System Windows_NT 10.0.22621
│ node-pre-gyp ERR! command "C:\\App\\scoop\\apps\\nodejs\\current\\node.exe" "D:\\Sync\\GitHub\\siyuan-packages-monorepo\\workspace\\node_modules\\.pnpm\\node-pre-gyp@0.14.0\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "rebuild"
│ node-pre-gyp ERR! cwd D:\Sync\GitHub\siyuan-packages-monorepo\workspace\node_modules\.pnpm\opencc@1.1.3\node_modules\opencc
│ Failed to execute 'node-gyp.cmd clean' (Error: spawn node-gyp.cmd ENOENT)
│ node-pre-gyp ERR! node -v v20.3.0
│ node-pre-gyp ERR! node-pre-gyp -v v0.14.0
│ node-pre-gyp ERR! not ok
└─ Failed in 2.8s at D:\Sync\GitHub\siyuan-packages-monorepo\workspace\node_modules\.pnpm\opencc@1.1.3\node_modules\opencc
 ELIFECYCLE  Command failed with exit code 1.
```
